name: se-online
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pylint
  - scikit-learn
  - pip
  - pandas
  - setuptools
  - plotly
  - plotly-orca
  - psutil
  - jupyter
  - tqdm
  - gdown # Required for stream51 dataset
  - pytorch
  - pip:
    - kaggle
    - matplotlib
    - JPype1
    - jax
    - jaxlib
    - git+https://github.com/online-ml/river
    # - -e file:ShrubEnsemble
    # - -e file:experiment_runner
    