name: psgd-ensemble
channels:
  - conda-forge
dependencies:
  - xsimd
  - xtl
  - xtensor
  - cmake
  - gcc_linux-64
  - gxx_linux-64
  - python=3.7 
  - numpy
  - pylint
  # - pandas
  # - pip
  # - setuptools
  # - pip:
  #   - pylint # For VSCode 
  #   - tqdm
  #   - ray
  #   - scikit-image
  #   - scikit-learn
  #   - scipy
  #   - -e file:./experiment_runner/
    